import { Bundler } from "../../bundler.ts";
import {
  assertEquals,
  assertStringIncludesIgnoreWhitespace,
} from "../../test_deps.ts";
import { defaultPlugins } from "../../_bundler_utils.ts";

Deno.test({
  name: "example → threejs",
  async fn() {
    const plugins = defaultPlugins();
    const bundler = new Bundler(plugins);
    bundler.logger.quiet = true;
    const input = "examples/threejs/src/index.html";
    const inputs = [
      input,
    ];
    const output =
      "dist/deps/ae8856d652293054080217dcd4a379a9209c4e88e3b4e2bff6c83bbd76af7bdd.js";
    const graph = await bundler.createGraph(inputs);

    assertEquals(
      graph,
      {
        "examples/threejs/src/index.html": [
          {
            "input": "examples/threejs/src/index.html",
            "output":
              "dist/deps/8a09bb0613db9a54f453394582c9c11ac8aab8427cfa0285043d754e7884dd42.html",
            "dependencies": {
              "examples/threejs/src/index.ts": {
                "Import": {},
              },
            },
            "export": {},
            "type": "Import",
          },
        ],
        "examples/threejs/src/index.ts": [
          {
            "input": "examples/threejs/src/index.ts",
            "output":
              "dist/deps/ae8856d652293054080217dcd4a379a9209c4e88e3b4e2bff6c83bbd76af7bdd.js",
            "dependencies": {
              "https://cdn.skypack.dev/three@0.130.0": {
                "Import": {
                  "specifiers": {
                    "BoxGeometry": "BoxGeometry",
                    "Mesh": "Mesh",
                    "MeshBasicMaterial": "MeshBasicMaterial",
                    "PerspectiveCamera": "PerspectiveCamera",
                    "Scene": "Scene",
                    "TextureLoader": "TextureLoader",
                    "WebGLRenderer": "WebGLRenderer",
                  },
                },
              },
            },
            "export": {},
            "type": "Import",
          },
        ],
        "https://cdn.skypack.dev/three@0.130.0": [
          {
            "input": "https://cdn.skypack.dev/three@0.130.0",
            "output":
              "dist/deps/26cc44bd654dd9c6696bb9675a3875bd9299c61bcb4c30f07497d1a3a42587ff.js",
            "dependencies": {
              "https://cdn.skypack.dev/-/three@v0.130.0-tRS2zGZSAezE0B1845w6/dist=es2020,mode=imports/optimized/three.js":
                {
                  "Import": {
                    "namespaces": [
                      "*",
                    ],
                    "specifiers": {
                      "default": "default",
                    },
                  },
                },
            },
            "export": {
              "namespaces": [
                "https://cdn.skypack.dev/-/three@v0.130.0-tRS2zGZSAezE0B1845w6/dist=es2020,mode=imports/optimized/three.js",
              ],
              "specifiers": {
                "default": "default",
              },
            },
            "type": "Import",
          },
        ],
        "https://cdn.skypack.dev/-/three@v0.130.0-tRS2zGZSAezE0B1845w6/dist=es2020,mode=imports/optimized/three.js":
          [
            {
              "input":
                "https://cdn.skypack.dev/-/three@v0.130.0-tRS2zGZSAezE0B1845w6/dist=es2020,mode=imports/optimized/three.js",
              "output":
                "dist/deps/c53f1e0b13dde873c2d9faac2122bb46c8b45594e555a6eb756ca0fb3938a674.js",
              "dependencies": {},
              "export": {
                "specifiers": {
                  "ACESFilmicToneMapping": "ACESFilmicToneMapping",
                  "AddEquation": "AddEquation",
                  "AddOperation": "AddOperation",
                  "AdditiveAnimationBlendMode": "AdditiveAnimationBlendMode",
                  "AdditiveBlending": "AdditiveBlending",
                  "AlphaFormat": "AlphaFormat",
                  "AlwaysDepth": "AlwaysDepth",
                  "AlwaysStencilFunc": "AlwaysStencilFunc",
                  "AmbientLight": "AmbientLight",
                  "AmbientLightProbe": "AmbientLightProbe",
                  "AnimationClip": "AnimationClip",
                  "AnimationLoader": "AnimationLoader",
                  "AnimationMixer": "AnimationMixer",
                  "AnimationObjectGroup": "AnimationObjectGroup",
                  "AnimationUtils": "AnimationUtils",
                  "ArcCurve": "ArcCurve",
                  "ArrayCamera": "ArrayCamera",
                  "ArrowHelper": "ArrowHelper",
                  "Audio": "Audio",
                  "AudioAnalyser": "AudioAnalyser",
                  "AudioContext": "AudioContext",
                  "AudioListener": "AudioListener",
                  "AudioLoader": "AudioLoader",
                  "AxesHelper": "AxesHelper",
                  "AxisHelper": "AxisHelper",
                  "BackSide": "BackSide",
                  "BasicDepthPacking": "BasicDepthPacking",
                  "BasicShadowMap": "BasicShadowMap",
                  "BinaryTextureLoader": "BinaryTextureLoader",
                  "Bone": "Bone",
                  "BooleanKeyframeTrack": "BooleanKeyframeTrack",
                  "BoundingBoxHelper": "BoundingBoxHelper",
                  "Box2": "Box2",
                  "Box3": "Box3",
                  "Box3Helper": "Box3Helper",
                  "BoxBufferGeometry": "BoxGeometry",
                  "BoxGeometry": "BoxGeometry",
                  "BoxHelper": "BoxHelper",
                  "BufferAttribute": "BufferAttribute",
                  "BufferGeometry": "BufferGeometry",
                  "BufferGeometryLoader": "BufferGeometryLoader",
                  "ByteType": "ByteType",
                  "Cache": "Cache",
                  "Camera": "Camera",
                  "CameraHelper": "CameraHelper",
                  "CanvasRenderer": "CanvasRenderer",
                  "CanvasTexture": "CanvasTexture",
                  "CatmullRomCurve3": "CatmullRomCurve3",
                  "CineonToneMapping": "CineonToneMapping",
                  "CircleBufferGeometry": "CircleGeometry",
                  "CircleGeometry": "CircleGeometry",
                  "ClampToEdgeWrapping": "ClampToEdgeWrapping",
                  "Clock": "Clock",
                  "Color": "Color",
                  "ColorKeyframeTrack": "ColorKeyframeTrack",
                  "CompressedTexture": "CompressedTexture",
                  "CompressedTextureLoader": "CompressedTextureLoader",
                  "ConeBufferGeometry": "ConeGeometry",
                  "ConeGeometry": "ConeGeometry",
                  "CubeCamera": "CubeCamera",
                  "CubeReflectionMapping": "CubeReflectionMapping",
                  "CubeRefractionMapping": "CubeRefractionMapping",
                  "CubeTexture": "CubeTexture",
                  "CubeTextureLoader": "CubeTextureLoader",
                  "CubeUVReflectionMapping": "CubeUVReflectionMapping",
                  "CubeUVRefractionMapping": "CubeUVRefractionMapping",
                  "CubicBezierCurve": "CubicBezierCurve",
                  "CubicBezierCurve3": "CubicBezierCurve3",
                  "CubicInterpolant": "CubicInterpolant",
                  "CullFaceBack": "CullFaceBack",
                  "CullFaceFront": "CullFaceFront",
                  "CullFaceFrontBack": "CullFaceFrontBack",
                  "CullFaceNone": "CullFaceNone",
                  "Curve": "Curve",
                  "CurvePath": "CurvePath",
                  "CustomBlending": "CustomBlending",
                  "CustomToneMapping": "CustomToneMapping",
                  "CylinderBufferGeometry": "CylinderGeometry",
                  "CylinderGeometry": "CylinderGeometry",
                  "Cylindrical": "Cylindrical",
                  "DataTexture": "DataTexture",
                  "DataTexture2DArray": "DataTexture2DArray",
                  "DataTexture3D": "DataTexture3D",
                  "DataTextureLoader": "DataTextureLoader",
                  "DataUtils": "DataUtils",
                  "DecrementStencilOp": "DecrementStencilOp",
                  "DecrementWrapStencilOp": "DecrementWrapStencilOp",
                  "DefaultLoadingManager": "DefaultLoadingManager",
                  "DepthFormat": "DepthFormat",
                  "DepthStencilFormat": "DepthStencilFormat",
                  "DepthTexture": "DepthTexture",
                  "DirectionalLight": "DirectionalLight",
                  "DirectionalLightHelper": "DirectionalLightHelper",
                  "DiscreteInterpolant": "DiscreteInterpolant",
                  "DodecahedronBufferGeometry": "DodecahedronGeometry",
                  "DodecahedronGeometry": "DodecahedronGeometry",
                  "DoubleSide": "DoubleSide",
                  "DstAlphaFactor": "DstAlphaFactor",
                  "DstColorFactor": "DstColorFactor",
                  "DynamicBufferAttribute": "DynamicBufferAttribute",
                  "DynamicCopyUsage": "DynamicCopyUsage",
                  "DynamicDrawUsage": "DynamicDrawUsage",
                  "DynamicReadUsage": "DynamicReadUsage",
                  "EdgesGeometry": "EdgesGeometry",
                  "EdgesHelper": "EdgesHelper",
                  "EllipseCurve": "EllipseCurve",
                  "EqualDepth": "EqualDepth",
                  "EqualStencilFunc": "EqualStencilFunc",
                  "EquirectangularReflectionMapping":
                    "EquirectangularReflectionMapping",
                  "EquirectangularRefractionMapping":
                    "EquirectangularRefractionMapping",
                  "Euler": "Euler",
                  "EventDispatcher": "EventDispatcher",
                  "ExtrudeBufferGeometry": "ExtrudeGeometry",
                  "ExtrudeGeometry": "ExtrudeGeometry",
                  "FaceColors": "FaceColors",
                  "FileLoader": "FileLoader",
                  "FlatShading": "FlatShading",
                  "Float16BufferAttribute": "Float16BufferAttribute",
                  "Float32Attribute": "Float32Attribute",
                  "Float32BufferAttribute": "Float32BufferAttribute",
                  "Float64Attribute": "Float64Attribute",
                  "Float64BufferAttribute": "Float64BufferAttribute",
                  "FloatType": "FloatType",
                  "Fog": "Fog",
                  "FogExp2": "FogExp2",
                  "Font": "Font",
                  "FontLoader": "FontLoader",
                  "FrontSide": "FrontSide",
                  "Frustum": "Frustum",
                  "GLBufferAttribute": "GLBufferAttribute",
                  "GLSL1": "GLSL1",
                  "GLSL3": "GLSL3",
                  "GammaEncoding": "GammaEncoding",
                  "GreaterDepth": "GreaterDepth",
                  "GreaterEqualDepth": "GreaterEqualDepth",
                  "GreaterEqualStencilFunc": "GreaterEqualStencilFunc",
                  "GreaterStencilFunc": "GreaterStencilFunc",
                  "GridHelper": "GridHelper",
                  "Group": "Group",
                  "HalfFloatType": "HalfFloatType",
                  "HemisphereLight": "HemisphereLight",
                  "HemisphereLightHelper": "HemisphereLightHelper",
                  "HemisphereLightProbe": "HemisphereLightProbe",
                  "IcosahedronBufferGeometry": "IcosahedronGeometry",
                  "IcosahedronGeometry": "IcosahedronGeometry",
                  "ImageBitmapLoader": "ImageBitmapLoader",
                  "ImageLoader": "ImageLoader",
                  "ImageUtils": "ImageUtils",
                  "ImmediateRenderObject": "ImmediateRenderObject",
                  "IncrementStencilOp": "IncrementStencilOp",
                  "IncrementWrapStencilOp": "IncrementWrapStencilOp",
                  "InstancedBufferAttribute": "InstancedBufferAttribute",
                  "InstancedBufferGeometry": "InstancedBufferGeometry",
                  "InstancedInterleavedBuffer": "InstancedInterleavedBuffer",
                  "InstancedMesh": "InstancedMesh",
                  "Int16Attribute": "Int16Attribute",
                  "Int16BufferAttribute": "Int16BufferAttribute",
                  "Int32Attribute": "Int32Attribute",
                  "Int32BufferAttribute": "Int32BufferAttribute",
                  "Int8Attribute": "Int8Attribute",
                  "Int8BufferAttribute": "Int8BufferAttribute",
                  "IntType": "IntType",
                  "InterleavedBuffer": "InterleavedBuffer",
                  "InterleavedBufferAttribute": "InterleavedBufferAttribute",
                  "Interpolant": "Interpolant",
                  "InterpolateDiscrete": "InterpolateDiscrete",
                  "InterpolateLinear": "InterpolateLinear",
                  "InterpolateSmooth": "InterpolateSmooth",
                  "InvertStencilOp": "InvertStencilOp",
                  "JSONLoader": "JSONLoader",
                  "KeepStencilOp": "KeepStencilOp",
                  "KeyframeTrack": "KeyframeTrack",
                  "LOD": "LOD",
                  "LatheBufferGeometry": "LatheGeometry",
                  "LatheGeometry": "LatheGeometry",
                  "Layers": "Layers",
                  "LensFlare": "LensFlare",
                  "LessDepth": "LessDepth",
                  "LessEqualDepth": "LessEqualDepth",
                  "LessEqualStencilFunc": "LessEqualStencilFunc",
                  "LessStencilFunc": "LessStencilFunc",
                  "Light": "Light",
                  "LightProbe": "LightProbe",
                  "Line": "Line",
                  "Line3": "Line3",
                  "LineBasicMaterial": "LineBasicMaterial",
                  "LineCurve": "LineCurve",
                  "LineCurve3": "LineCurve3",
                  "LineDashedMaterial": "LineDashedMaterial",
                  "LineLoop": "LineLoop",
                  "LinePieces": "LinePieces",
                  "LineSegments": "LineSegments",
                  "LineStrip": "LineStrip",
                  "LinearEncoding": "LinearEncoding",
                  "LinearFilter": "LinearFilter",
                  "LinearInterpolant": "LinearInterpolant",
                  "LinearMipMapLinearFilter": "LinearMipMapLinearFilter",
                  "LinearMipMapNearestFilter": "LinearMipMapNearestFilter",
                  "LinearMipmapLinearFilter": "LinearMipmapLinearFilter",
                  "LinearMipmapNearestFilter": "LinearMipmapNearestFilter",
                  "LinearToneMapping": "LinearToneMapping",
                  "Loader": "Loader",
                  "LoaderUtils": "LoaderUtils",
                  "LoadingManager": "LoadingManager",
                  "LogLuvEncoding": "LogLuvEncoding",
                  "LoopOnce": "LoopOnce",
                  "LoopPingPong": "LoopPingPong",
                  "LoopRepeat": "LoopRepeat",
                  "LuminanceAlphaFormat": "LuminanceAlphaFormat",
                  "LuminanceFormat": "LuminanceFormat",
                  "MOUSE": "MOUSE",
                  "Material": "Material",
                  "MaterialLoader": "MaterialLoader",
                  "Math": "MathUtils",
                  "MathUtils": "MathUtils",
                  "Matrix3": "Matrix3",
                  "Matrix4": "Matrix4",
                  "MaxEquation": "MaxEquation",
                  "Mesh": "Mesh",
                  "MeshBasicMaterial": "MeshBasicMaterial",
                  "MeshDepthMaterial": "MeshDepthMaterial",
                  "MeshDistanceMaterial": "MeshDistanceMaterial",
                  "MeshFaceMaterial": "MeshFaceMaterial",
                  "MeshLambertMaterial": "MeshLambertMaterial",
                  "MeshMatcapMaterial": "MeshMatcapMaterial",
                  "MeshNormalMaterial": "MeshNormalMaterial",
                  "MeshPhongMaterial": "MeshPhongMaterial",
                  "MeshPhysicalMaterial": "MeshPhysicalMaterial",
                  "MeshStandardMaterial": "MeshStandardMaterial",
                  "MeshToonMaterial": "MeshToonMaterial",
                  "MinEquation": "MinEquation",
                  "MirroredRepeatWrapping": "MirroredRepeatWrapping",
                  "MixOperation": "MixOperation",
                  "MultiMaterial": "MultiMaterial",
                  "MultiplyBlending": "MultiplyBlending",
                  "MultiplyOperation": "MultiplyOperation",
                  "NearestFilter": "NearestFilter",
                  "NearestMipMapLinearFilter": "NearestMipMapLinearFilter",
                  "NearestMipMapNearestFilter": "NearestMipMapNearestFilter",
                  "NearestMipmapLinearFilter": "NearestMipmapLinearFilter",
                  "NearestMipmapNearestFilter": "NearestMipmapNearestFilter",
                  "NeverDepth": "NeverDepth",
                  "NeverStencilFunc": "NeverStencilFunc",
                  "NoBlending": "NoBlending",
                  "NoColors": "NoColors",
                  "NoToneMapping": "NoToneMapping",
                  "NormalAnimationBlendMode": "NormalAnimationBlendMode",
                  "NormalBlending": "NormalBlending",
                  "NotEqualDepth": "NotEqualDepth",
                  "NotEqualStencilFunc": "NotEqualStencilFunc",
                  "NumberKeyframeTrack": "NumberKeyframeTrack",
                  "Object3D": "Object3D",
                  "ObjectLoader": "ObjectLoader",
                  "ObjectSpaceNormalMap": "ObjectSpaceNormalMap",
                  "OctahedronBufferGeometry": "OctahedronGeometry",
                  "OctahedronGeometry": "OctahedronGeometry",
                  "OneFactor": "OneFactor",
                  "OneMinusDstAlphaFactor": "OneMinusDstAlphaFactor",
                  "OneMinusDstColorFactor": "OneMinusDstColorFactor",
                  "OneMinusSrcAlphaFactor": "OneMinusSrcAlphaFactor",
                  "OneMinusSrcColorFactor": "OneMinusSrcColorFactor",
                  "OrthographicCamera": "OrthographicCamera",
                  "PCFShadowMap": "PCFShadowMap",
                  "PCFSoftShadowMap": "PCFSoftShadowMap",
                  "PMREMGenerator": "PMREMGenerator",
                  "ParametricBufferGeometry": "ParametricGeometry",
                  "ParametricGeometry": "ParametricGeometry",
                  "Particle": "Particle",
                  "ParticleBasicMaterial": "ParticleBasicMaterial",
                  "ParticleSystem": "ParticleSystem",
                  "ParticleSystemMaterial": "ParticleSystemMaterial",
                  "Path": "Path",
                  "PerspectiveCamera": "PerspectiveCamera",
                  "Plane": "Plane",
                  "PlaneBufferGeometry": "PlaneGeometry",
                  "PlaneGeometry": "PlaneGeometry",
                  "PlaneHelper": "PlaneHelper",
                  "PointCloud": "PointCloud",
                  "PointCloudMaterial": "PointCloudMaterial",
                  "PointLight": "PointLight",
                  "PointLightHelper": "PointLightHelper",
                  "Points": "Points",
                  "PointsMaterial": "PointsMaterial",
                  "PolarGridHelper": "PolarGridHelper",
                  "PolyhedronBufferGeometry": "PolyhedronGeometry",
                  "PolyhedronGeometry": "PolyhedronGeometry",
                  "PositionalAudio": "PositionalAudio",
                  "PropertyBinding": "PropertyBinding",
                  "PropertyMixer": "PropertyMixer",
                  "QuadraticBezierCurve": "QuadraticBezierCurve",
                  "QuadraticBezierCurve3": "QuadraticBezierCurve3",
                  "Quaternion": "Quaternion",
                  "QuaternionKeyframeTrack": "QuaternionKeyframeTrack",
                  "QuaternionLinearInterpolant": "QuaternionLinearInterpolant",
                  "REVISION": "REVISION",
                  "RGBADepthPacking": "RGBADepthPacking",
                  "RGBAFormat": "RGBAFormat",
                  "RGBAIntegerFormat": "RGBAIntegerFormat",
                  "RGBA_ASTC_10x10_Format": "RGBA_ASTC_10x10_Format",
                  "RGBA_ASTC_10x5_Format": "RGBA_ASTC_10x5_Format",
                  "RGBA_ASTC_10x6_Format": "RGBA_ASTC_10x6_Format",
                  "RGBA_ASTC_10x8_Format": "RGBA_ASTC_10x8_Format",
                  "RGBA_ASTC_12x10_Format": "RGBA_ASTC_12x10_Format",
                  "RGBA_ASTC_12x12_Format": "RGBA_ASTC_12x12_Format",
                  "RGBA_ASTC_4x4_Format": "RGBA_ASTC_4x4_Format",
                  "RGBA_ASTC_5x4_Format": "RGBA_ASTC_5x4_Format",
                  "RGBA_ASTC_5x5_Format": "RGBA_ASTC_5x5_Format",
                  "RGBA_ASTC_6x5_Format": "RGBA_ASTC_6x5_Format",
                  "RGBA_ASTC_6x6_Format": "RGBA_ASTC_6x6_Format",
                  "RGBA_ASTC_8x5_Format": "RGBA_ASTC_8x5_Format",
                  "RGBA_ASTC_8x6_Format": "RGBA_ASTC_8x6_Format",
                  "RGBA_ASTC_8x8_Format": "RGBA_ASTC_8x8_Format",
                  "RGBA_BPTC_Format": "RGBA_BPTC_Format",
                  "RGBA_ETC2_EAC_Format": "RGBA_ETC2_EAC_Format",
                  "RGBA_PVRTC_2BPPV1_Format": "RGBA_PVRTC_2BPPV1_Format",
                  "RGBA_PVRTC_4BPPV1_Format": "RGBA_PVRTC_4BPPV1_Format",
                  "RGBA_S3TC_DXT1_Format": "RGBA_S3TC_DXT1_Format",
                  "RGBA_S3TC_DXT3_Format": "RGBA_S3TC_DXT3_Format",
                  "RGBA_S3TC_DXT5_Format": "RGBA_S3TC_DXT5_Format",
                  "RGBDEncoding": "RGBDEncoding",
                  "RGBEEncoding": "RGBEEncoding",
                  "RGBEFormat": "RGBEFormat",
                  "RGBFormat": "RGBFormat",
                  "RGBIntegerFormat": "RGBIntegerFormat",
                  "RGBM16Encoding": "RGBM16Encoding",
                  "RGBM7Encoding": "RGBM7Encoding",
                  "RGB_ETC1_Format": "RGB_ETC1_Format",
                  "RGB_ETC2_Format": "RGB_ETC2_Format",
                  "RGB_PVRTC_2BPPV1_Format": "RGB_PVRTC_2BPPV1_Format",
                  "RGB_PVRTC_4BPPV1_Format": "RGB_PVRTC_4BPPV1_Format",
                  "RGB_S3TC_DXT1_Format": "RGB_S3TC_DXT1_Format",
                  "RGFormat": "RGFormat",
                  "RGIntegerFormat": "RGIntegerFormat",
                  "RawShaderMaterial": "RawShaderMaterial",
                  "Ray": "Ray",
                  "Raycaster": "Raycaster",
                  "RectAreaLight": "RectAreaLight",
                  "RedFormat": "RedFormat",
                  "RedIntegerFormat": "RedIntegerFormat",
                  "ReinhardToneMapping": "ReinhardToneMapping",
                  "RepeatWrapping": "RepeatWrapping",
                  "ReplaceStencilOp": "ReplaceStencilOp",
                  "ReverseSubtractEquation": "ReverseSubtractEquation",
                  "RingBufferGeometry": "RingGeometry",
                  "RingGeometry": "RingGeometry",
                  "SRGB8_ALPHA8_ASTC_10x10_Format":
                    "SRGB8_ALPHA8_ASTC_10x10_Format",
                  "SRGB8_ALPHA8_ASTC_10x5_Format":
                    "SRGB8_ALPHA8_ASTC_10x5_Format",
                  "SRGB8_ALPHA8_ASTC_10x6_Format":
                    "SRGB8_ALPHA8_ASTC_10x6_Format",
                  "SRGB8_ALPHA8_ASTC_10x8_Format":
                    "SRGB8_ALPHA8_ASTC_10x8_Format",
                  "SRGB8_ALPHA8_ASTC_12x10_Format":
                    "SRGB8_ALPHA8_ASTC_12x10_Format",
                  "SRGB8_ALPHA8_ASTC_12x12_Format":
                    "SRGB8_ALPHA8_ASTC_12x12_Format",
                  "SRGB8_ALPHA8_ASTC_4x4_Format":
                    "SRGB8_ALPHA8_ASTC_4x4_Format",
                  "SRGB8_ALPHA8_ASTC_5x4_Format":
                    "SRGB8_ALPHA8_ASTC_5x4_Format",
                  "SRGB8_ALPHA8_ASTC_5x5_Format":
                    "SRGB8_ALPHA8_ASTC_5x5_Format",
                  "SRGB8_ALPHA8_ASTC_6x5_Format":
                    "SRGB8_ALPHA8_ASTC_6x5_Format",
                  "SRGB8_ALPHA8_ASTC_6x6_Format":
                    "SRGB8_ALPHA8_ASTC_6x6_Format",
                  "SRGB8_ALPHA8_ASTC_8x5_Format":
                    "SRGB8_ALPHA8_ASTC_8x5_Format",
                  "SRGB8_ALPHA8_ASTC_8x6_Format":
                    "SRGB8_ALPHA8_ASTC_8x6_Format",
                  "SRGB8_ALPHA8_ASTC_8x8_Format":
                    "SRGB8_ALPHA8_ASTC_8x8_Format",
                  "Scene": "Scene",
                  "SceneUtils": "SceneUtils",
                  "ShaderChunk": "ShaderChunk",
                  "ShaderLib": "ShaderLib",
                  "ShaderMaterial": "ShaderMaterial",
                  "ShadowMaterial": "ShadowMaterial",
                  "Shape": "Shape",
                  "ShapeBufferGeometry": "ShapeGeometry",
                  "ShapeGeometry": "ShapeGeometry",
                  "ShapePath": "ShapePath",
                  "ShapeUtils": "ShapeUtils",
                  "ShortType": "ShortType",
                  "Skeleton": "Skeleton",
                  "SkeletonHelper": "SkeletonHelper",
                  "SkinnedMesh": "SkinnedMesh",
                  "SmoothShading": "SmoothShading",
                  "Sphere": "Sphere",
                  "SphereBufferGeometry": "SphereGeometry",
                  "SphereGeometry": "SphereGeometry",
                  "Spherical": "Spherical",
                  "SphericalHarmonics3": "SphericalHarmonics3",
                  "SplineCurve": "SplineCurve",
                  "SpotLight": "SpotLight",
                  "SpotLightHelper": "SpotLightHelper",
                  "Sprite": "Sprite",
                  "SpriteMaterial": "SpriteMaterial",
                  "SrcAlphaFactor": "SrcAlphaFactor",
                  "SrcAlphaSaturateFactor": "SrcAlphaSaturateFactor",
                  "SrcColorFactor": "SrcColorFactor",
                  "StaticCopyUsage": "StaticCopyUsage",
                  "StaticDrawUsage": "StaticDrawUsage",
                  "StaticReadUsage": "StaticReadUsage",
                  "StereoCamera": "StereoCamera",
                  "StreamCopyUsage": "StreamCopyUsage",
                  "StreamDrawUsage": "StreamDrawUsage",
                  "StreamReadUsage": "StreamReadUsage",
                  "StringKeyframeTrack": "StringKeyframeTrack",
                  "SubtractEquation": "SubtractEquation",
                  "SubtractiveBlending": "SubtractiveBlending",
                  "TOUCH": "TOUCH",
                  "TangentSpaceNormalMap": "TangentSpaceNormalMap",
                  "TetrahedronBufferGeometry": "TetrahedronGeometry",
                  "TetrahedronGeometry": "TetrahedronGeometry",
                  "TextBufferGeometry": "TextGeometry",
                  "TextGeometry": "TextGeometry",
                  "Texture": "Texture",
                  "TextureLoader": "TextureLoader",
                  "TorusBufferGeometry": "TorusGeometry",
                  "TorusGeometry": "TorusGeometry",
                  "TorusKnotBufferGeometry": "TorusKnotGeometry",
                  "TorusKnotGeometry": "TorusKnotGeometry",
                  "Triangle": "Triangle",
                  "TriangleFanDrawMode": "TriangleFanDrawMode",
                  "TriangleStripDrawMode": "TriangleStripDrawMode",
                  "TrianglesDrawMode": "TrianglesDrawMode",
                  "TubeBufferGeometry": "TubeGeometry",
                  "TubeGeometry": "TubeGeometry",
                  "UVMapping": "UVMapping",
                  "Uint16Attribute": "Uint16Attribute",
                  "Uint16BufferAttribute": "Uint16BufferAttribute",
                  "Uint32Attribute": "Uint32Attribute",
                  "Uint32BufferAttribute": "Uint32BufferAttribute",
                  "Uint8Attribute": "Uint8Attribute",
                  "Uint8BufferAttribute": "Uint8BufferAttribute",
                  "Uint8ClampedAttribute": "Uint8ClampedAttribute",
                  "Uint8ClampedBufferAttribute": "Uint8ClampedBufferAttribute",
                  "Uniform": "Uniform",
                  "UniformsLib": "UniformsLib",
                  "UniformsUtils": "UniformsUtils",
                  "UnsignedByteType": "UnsignedByteType",
                  "UnsignedInt248Type": "UnsignedInt248Type",
                  "UnsignedIntType": "UnsignedIntType",
                  "UnsignedShort4444Type": "UnsignedShort4444Type",
                  "UnsignedShort5551Type": "UnsignedShort5551Type",
                  "UnsignedShort565Type": "UnsignedShort565Type",
                  "UnsignedShortType": "UnsignedShortType",
                  "VSMShadowMap": "VSMShadowMap",
                  "Vector2": "Vector2",
                  "Vector3": "Vector3",
                  "Vector4": "Vector4",
                  "VectorKeyframeTrack": "VectorKeyframeTrack",
                  "Vertex": "Vertex",
                  "VertexColors": "VertexColors",
                  "VideoTexture": "VideoTexture",
                  "WebGL1Renderer": "WebGL1Renderer",
                  "WebGLCubeRenderTarget": "WebGLCubeRenderTarget",
                  "WebGLMultipleRenderTargets": "WebGLMultipleRenderTargets",
                  "WebGLMultisampleRenderTarget":
                    "WebGLMultisampleRenderTarget",
                  "WebGLRenderTarget": "WebGLRenderTarget",
                  "WebGLRenderTargetCube": "WebGLRenderTargetCube",
                  "WebGLRenderer": "WebGLRenderer",
                  "WebGLUtils": "WebGLUtils",
                  "WireframeGeometry": "WireframeGeometry",
                  "WireframeHelper": "WireframeHelper",
                  "WrapAroundEnding": "WrapAroundEnding",
                  "XHRLoader": "XHRLoader",
                  "ZeroCurvatureEnding": "ZeroCurvatureEnding",
                  "ZeroFactor": "ZeroFactor",
                  "ZeroSlopeEnding": "ZeroSlopeEnding",
                  "ZeroStencilOp": "ZeroStencilOp",
                  "sRGBEncoding": "sRGBEncoding",
                },
                "default": true,
              },
              "type": "Import",
            },
          ],
      },
    );

    const chunks = await bundler.createChunks(inputs, graph);

    assertEquals(chunks, [
      {
        dependencyItems: [
          ,
        ],
        item: {
          history: [
            "examples/threejs/src/index.html",
          ],
          type: "Import",
        },
      },
      {
        dependencyItems: [
          {
            history: [
              "https://cdn.skypack.dev/three@0.130.0",
              "examples/threejs/src/index.ts",
              "examples/threejs/src/index.html",
            ],
            type: "Import",
          },
        ],
        item: {
          history: [
            "examples/threejs/src/index.ts",
            "examples/threejs/src/index.html",
          ],
          type: "Import",
        },
      },
    ]);
    const bundles = await bundler.createBundles(chunks, graph, {
      reload: true,
    });

    assertEquals(Object.keys(bundles).length, 2);

    const bundle = bundles[output] as string;

    assertStringIncludesIgnoreWhitespace(
      bundle,
      `const mod = (async () => {
        const { default: _default } = await mod1;
        return { default: _default, ...await mod1 };
      })();`,
    );
    assertStringIncludesIgnoreWhitespace(
      bundle,
      `export default (async () => {
        const { BoxGeometry, Mesh, MeshBasicMaterial, PerspectiveCamera, Scene, TextureLoader, WebGLRenderer } = await mod;
        const scene = new Scene();
        const camera = new PerspectiveCamera(75, window.innerWidth / window.innerHeight, 0.1, 1000);
        camera.position.z = 4;
        const renderer = new WebGLRenderer({ antialias: true });
        renderer.setClearColor("#000000");
        renderer.setSize(window.innerWidth, window.innerHeight);
        document.body.appendChild(renderer.domElement);
        function loadTexture(url) {
            const loader = new TextureLoader();
            return new Promise((resolve) => loader.load(url, resolve));
        }
        const texture = await loadTexture("./image.png");
        const geometry = new BoxGeometry(1, 1, 1);
        const material = new MeshBasicMaterial({ color: "#433F81", map: texture });
        const cube = new Mesh(geometry, material);
        scene.add(cube);
        const render = function () {
            requestAnimationFrame(render);
            cube.rotation.x += 0.01;
            cube.rotation.y += 0.01;
            renderer.render(scene, camera);
        };
        render();
        return {};
    })();`,
    );
  },
});
